### ISSUE TITLE
Cannot work after the update(21-11-05)

### ISSUE THREAD

**Issue by K4rl-M4rx** [Jinwen-XU/ProjLib#2]
After the update, my previous work won't compile and give warnings:

> Package xkeyval: 'disable' undefined in families 'MTX'.
> Package xkeyval: 'enable' undefined in families 'MTX'.

I tried a test run using a basic MWE, it returns the same warnings. 

Here is my MWE:

```
\documentclass{amsart}
\usepackage[a4paper,margin=.75in]{geometry}
\usepackage[hidelinks]{hyperref}
\usepackage[palatino]{ProjLib}

\begin{document}

Hello

\end{document}
```

I am currently using updated miktex on MacOS Monterey.

**Comment by Jinwen-XU** [comment]
This is because in the newest microtype 3.0, the keys `disable` and `enable` have been renamed into `deactivate` and `reactivate`. I'm working on this issue and should be able to fix it today.

**Comment by Jinwen-XU** [comment]
This has been fixed in version 2021/11/09, which should be available on CTAN by tomorrow (November 10, 2021).
